export { default as logo } from "./logo.svg";
export { default as logo2 } from "./logo2.svg";
export { default as logo3 } from "./logo3.svg";
export { default as bgLogo } from "./bgLogo.svg";
export { default as plane } from "./plane.svg";
export { default as bgGradient } from "./gradientBackground.svg";
export { default as OptionalInsurance } from "./OptionalInsurance.svg";
export { default as RealTimeChat } from "./RealTimeChat.svg";
export { default as SameDayDelivery } from "./SameDayDelivery.svg";
export { default as SecurePayments } from "./SecurePayments.svg";
export { default as VerifiedCarriers } from "./VerifiedCarriers.svg";
export { default as FlexiblePricing } from "./FlexiblePricing.svg";
export {default as trackPackage} from "./trackPackage.svg";
export {default as chooseCarrier} from "./chooseCarrier.svg";
export {default as getMatched} from "./getMatched.svg";
export {default as postPackage} from "./postPackage.svg";
export {default as insurance} from "./insurance.svg";
export {default as ratings} from "./ratings.svg";
export {default as verifiedIdentities} from "./verifiedIdentities.svg";
export {default as escrowProtection} from "./escrowProtection.svg";
export {default as builtForTrust} from "./BuiltForTrust.svg";
export {default as sender} from "./sender.svg";
export {default as carrier} from "./carrier.svg";
export {default as star} from "./star.svg";
export {default as cloudSmall} from "./cloudSmall.svg";
export {default as cloudLarge} from "./cloudLarge.svg";
export {default as package} from "./package.svg";
export {default as luggage} from "./luggage.svg";
export {default as hourglass} from "./hourglass.svg";
export {default as OG} from "./OG.png";